routes/mail.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *
from models.mail import Mail


main = Blueprint('mail', __name__)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    mail = Mail.new(form)
    # 为了安全
    mail.set_sender(current_user().id)
    return redirect(url_for(".index"))


@main.route("/", methods=["GET"])
def index():
    u = current_user()
    send_mail = Mail.find_all(sender_id=u.id)
    received_mail = Mail.find_all(receiver_id=u.id)

    return render_template("mail/mail_index.html", user=u, sends=send_mail, receives=received_mail)


@main.route("/view/<int:id>")
def view(id):
    mail = Mail.find(id)
    # 不是你自己发的，你肯定不能看
    # 不是收的人，那你看了也不会变成已读
    if current_user().id == mail.receiver_id:
        mail.mark_read()
    if current_user().id in [mail.receiver_id, mail.sender_id]:
        return render_template("mail/mail_detail.html", mail=mail)
    else:
        return redirect(url_for(".index"))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    send_from_directory,
    abort,
)

from routes import *

from models.topic import Topic
from models.board import Board

from utils import allow_file
from models.user import User
from werkzeug.utils import secure_filename
from config import user_file_director
import os
import uuid


main = Blueprint('topic', __name__)

csrf_tokens = dict()


def current_user():
    # 从 session 中找到 user_id 字段, 找不到就 -1
    # 然后 User.find_by 来用 id 找用户
    # 找不到就返回 None
    uid = session.get('user_id', -1)
    u = User.find_by(id=uid)
    return u


# Topic
@main.route("/")
def index():
    # board_id = 2
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        # ms = Topic.all()
        ms = Topic.cache_all()
        # ms = Topic.all_delay()
    else:
        ms = Topic.find_all(board_id=board_id)
        # ms = Topic.cache_find(board_id)
    token = str(uuid.uuid4())
    u = current_user()
    if u is None:
        return redirect(url_for('.signin'))
    else:
        csrf_tokens['token'] = u.id
        bs = Board.all()
        return render_template("topic/index.html", user=u, ms=ms, token=token, bs=bs)


@main.route('/topic/<int:id>')
def detail(id):
    u = current_user()
    m = Topic.get(id)
    other_topic = m.other_topic()

    return render_template("topic/detail.html", user=u, topic=m, other_topic=other_topic)


@main.route("/topic/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()
    m = Topic.new(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/topic/delete")
def delete():
    id = int(request.args.get('id'))
    token = request.args.get('token')
    u = current_user()
    # 判断 token 是否是我们给的
    if token in csrf_tokens and csrf_tokens[token] == u.id:
        csrf_tokens.pop(token)
        if u is not None:
            print('删除 topic 用户是', u, id)
            Topic.delete(id)
            return redirect(url_for('.index'))
        else:
            abort(404)
    else:
        abort(403)


@main.route("/topic/new")
def new():
    u = current_user()
    bs = Board.all()
    return render_template("topic/new.html", user=u, bs=bs)


# login
@main.route("/signin")
def signin():
    u = current_user()
    return render_template("index.html", user=u)


@main.route("/register", methods=['POST'])
def register():
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.signin'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('.signin'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('.index'))


@main.route("/key_login", methods=['POST'])
def key_login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('topic.index'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('topic.index'))


# setting
@main.route('/setting')
def setting():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        return render_template('profile.html', user=u)


@main.route('/setting/user', methods=['POST'])
def setting_user():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        u.update(request.form)
        return redirect(url_for(".setting"))


@main.route('/addimg', methods=["POST"])
def add_img():
    u = current_user()

    if u is None:
        return redirect(url_for(".setting"))

    if 'file' not in request.files:
        return redirect(request.url)

    file = request.files['file']
    if file.filename == '':
        return redirect(request.url)

    if allow_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(user_file_director, filename))
        u.user_image = filename
        u.save()

    return redirect(url_for(".setting"))


@main.route("/uploads/<filename>")
def uploads(filename):
    return send_from_directory(user_file_director, filename)


@main.route("/logout")
def log_out():
    session.pop("user_id")
    return redirect(url_for(".index"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>base.html</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
{% block navbar %}
<!-- navbar -->
<div class='navbar'>
    <div class='navbar-inner'>
        <div class='container'>
            <a class='brand' href='/'>

                <img src="//o4j806krb.qnssl.com/public/images/cnodejs_light.svg"/>

            </a>

            <form id='search_form' class='navbar-search' action="/search">
                <input type='text' id='q' name='q' class='search-query span3' value=''/>
            </form>
            <ul class='nav pull-right'>
                <li><a href='{{url_for('topic.index')}}'>首页</a></li>
                <li><a href='{{url_for('mail.index')}}'>站内私信</a></li>
                <li><a href="" target="">关于</a></li>
                <li><a href='{{url_for('topic.setting')}}'>设置</a></li>
                <li><a href='{{url_for('topic.log_out')}}'>退出</a></li>

            </ul>
            <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                <span class="icon-bar"></span>q
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
        </div>
    </div>
</div>
{% endblock %}
<div id="main">
    {% block sidebar %}
        <div id="sidebar">
            <div class="panel">
                <div class="header">
                    <span class="col_fade">个人信息</span>
                </div>
                <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="/user/{{ user.username }}">
                            <img src={{"/uploads/" + user.user_image + '?v=3&amp;s=120'}} title="user.user_image">
                        </a>
                        <span class="user_name"><a class="dark" href="/user/{{ user.username }}">{{ user.username }}</a></span>

                        <div class="board clearfix">
                            <div class="floor">
                                <span class="big">积分: 0 </span>
                            </div>
                        </div>
                        <div class="space clearfix"></div>
                        <span class="signature">
                            {{ user.user_idiograph }}
                        </span>
                    </div>
                </div>
            </div>
            </div>
            <div class="panel">
                    <div class="inner">
                        <a href="/topic/new" class="create_topic_btn">
                            <span class="span-success">发布话题</span>
                        </a>
                    </div>
                </div>
        </div>
    {% endblock %}

    {% block content %}
    {% endblock %}
</div>

{% block footer %}
<div id="footer">
    <div id="footer_main">
        <div class="links">
            <a class="dark" href="/rss">RSS</a>
            |
            <a class="dark" href="https://github.com/cnodejs/nodeclub/">源码地址</a>
        </div>

        <div class="col_fade">

            <p>CNode 社区为国内最专业的 Node.js 开源技术社区，致力于 Node.js 的技术研究。</p>
            <p>服务器赞助商为
                <a href="http://www.ucloud.cn/?utm_source=zanzhu&amp;utm_campaign=cnodejs&amp;utm_medium=display&amp;utm_content=yejiao&amp;ytag=cnodejs_logo"
                   target="_blank" class="sponsor_outlink" data-label="ucloud_bottom">
                    <img src="//dn-cnode.qbox.me/FuIpEaM9bvsZKnQ3QfPtBHWQmLM9" title="ucloud" alt="ucloud" width="92px">
                </a>
                ，存储赞助商为
                <a href="http://www.qiniu.com/?ref=cnode" target="_blank" class="sponsor_outlink"
                   data-label="qiniu_bottom">
                    <img src="//dn-cnode.qbox.me/Fg0jtDIcTqVC049oVu5-sn6Om4NX" title="七牛云存储" alt="七牛云存储" width="115px">
                </a>
                ，由<a href="https://alinode.aliyun.com/?ref=cnode" target="_blank" class="sponsor_outlink"
                     data-label="alinode_bottom">
                    <img src="//dn-cnode.qbox.me/FpMZk31PDyxkC8yStmMQL4XroaGD" title="alinode" alt="alinode"
                         height="54px" width="166px">
                </a>提供应用性能服务。
            </p>
            <p>新手搭建 Node.js 服务器，推荐使用无需备案的 <a href="https://www.digitalocean.com/?refcode=eba02656eeb3">DigitalOcean(https://www.digitalocean.com/)</a>
            </p>
        </div>


    </div>
</div>
{% endblock %}

{% block script %}
{% endblock %}

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!-- This file has been downloaded from Bootsnipp.com. Enjoy! -->
    <title>Login and Register tabbed form - Bootstrap.cn</title>
    <!--<meta name="viewport" content="width=device-width, initial-scale=1">-->
    <link href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
        body {
    padding-top: 90px;
}
.panel-login {
	border-color: #ccc;
	-webkit-box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);
	-moz-box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);
	box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);
}
.panel-login>.panel-heading {
	color: #00415d;
	background-color: #fff;
	border-color: #fff;
	text-align:center;
}
.panel-login>.panel-heading a{
	text-decoration: none;
	color: #666;
	font-weight: bold;
	font-size: 15px;
	-webkit-transition: all 0.1s linear;
	-moz-transition: all 0.1s linear;
	transition: all 0.1s linear;
}
.panel-login>.panel-heading a.active{
	color: #029f5b;
	font-size: 18px;
}
.panel-login>.panel-heading hr{
	margin-top: 10px;
	margin-bottom: 0px;
	clear: both;
	border: 0;
	height: 1px;
	background-image: -webkit-linear-gradient(left,rgba(0, 0, 0, 0),rgba(0, 0, 0, 0.15),rgba(0, 0, 0, 0));
	background-image: -moz-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));
	background-image: -ms-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));
	background-image: -o-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));
}
.panel-login input[type="text"],.panel-login input[type="email"],.panel-login input[type="password"] {
	height: 45px;
	border: 1px solid #ddd;
	font-size: 16px;
	-webkit-transition: all 0.1s linear;
	-moz-transition: all 0.1s linear;
	transition: all 0.1s linear;
}
.panel-login input:hover,
.panel-login input:focus {
	outline:none;
	-webkit-box-shadow: none;
	-moz-box-shadow: none;
	box-shadow: none;
	border-color: #ccc;
}
.btn-login {
	background-color: #59B2E0;
	outline: none;
	color: #fff;
	font-size: 14px;
	height: auto;
	font-weight: normal;
	padding: 14px 0;
	text-transform: uppercase;
	border-color: #59B2E6;
}
.btn-login:hover,
.btn-login:focus {
	color: #fff;
	background-color: #53A3CD;
	border-color: #53A3CD;
}
.forgot-password {
	text-decoration: underline;
	color: #888;
}
.forgot-password:hover,
.forgot-password:focus {
	text-decoration: underline;
	color: #666;
}

.btn-register {
	background-color: #1CB94E;
	outline: none;
	color: #fff;
	font-size: 14px;
	height: auto;
	font-weight: normal;
	padding: 14px 0;
	text-transform: uppercase;
	border-color: #1CB94A;
}
.btn-register:hover,
.btn-register:focus {
	color: #fff;
	background-color: #1CA347;
	border-color: #1CA347;
}

    </style>
    <script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
    	<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="panel panel-login">
					<div class="panel-heading">
						<div class="row">
							<div class="col-xs-6">
								<a href="#" class="active" id="login-form-link">登录</a>
							</div>
							<div class="col-xs-6">
								<a href="#" id="register-form-link">注册</a>
							</div>
						</div>
						<hr>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-12">
                                <div id="login-form">
                                    <form action="{{ url_for('.login') }}" method="post" role="form" style="display: block;">
                                        <div class="form-group">
                                            <input type="text" name="username" id="name" tabindex="1" class="form-control" placeholder="用户名" value="">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" name="password" id="ps" tabindex="2" class="form-control" placeholder="密码">
                                        </div>
                                    <div class="form-group">
                                            <div class="row">
                                                <div class="col-sm-6 col-sm-offset-3">
                                                    <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="登录">
                                                </div>
                                            </div>
                                    </div>
                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                      <div class="row">
                                         <div class="col-sm-6 col-sm-offset-3">
                                             <!-- 一键登录 -->
                                             <form class="form-horizontal" method="post" action="{{ url_for('.key_login') }}">
                                                <input type="hidden" class="input-xlarge" value="test" name="username">
                                                <input type="hidden" class="input-xlarge" value="test" name="password">
                                                <div class="form-actions">
                                                    <input type="submit" name="login-submit" tabindex="4" class="form-control btn btn-login" value="一键登录">
                                                </div>
                                            </form>
                                         </div>
                                      </div>
                                </div>

								<form id="register-form" action="{{ url_for('.register') }}" method="post" role="form" style="display: none;">
									<div class="form-group">
										<input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="用户名" value="">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="密码">
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="注册">
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
<script type="text/javascript">
$(function() {

    $('#login-form-link').click(function(e) {
		$("#login-form").delay(100).fadeIn(100);
 		$("#register-form").fadeOut(100);
		$('#register-form-link').removeClass('active');
		$(this).addClass('active');
		e.preventDefault();
	});
	$('#register-form-link').click(function(e) {
		$("#register-form").delay(100).fadeIn(100);
 		$("#login-form").fadeOut(100);
		$('#login-form-link').removeClass('active');
		$(this).addClass('active');
		e.preventDefault();
	});

});
</script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action={{ url_for(".login") }}>
    <input type="text" name="user_name" placeholder="user_name">
    <button type="submit">提交</button>
</form>
</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>setting</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
{% extends "base.html"%}
<div id="main">

    {% block content %}
    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="{{url_for('topic.index')}}">主页</a><span class="divider">/</span></li>
                    <li class="active">设置</li>
                </ul>
            </div>
            <div class="inner">


                <form id="setting_form" class="form-horizontal" action={{url_for('topic.setting_user')}} method="post">
                    <div class="control-group">
                        <label class="control-label" for="name">用户名</label>

                        <div class="controls">
                            <input class="input-xlarge readonly" id="name" size="30" type="text"
                                   readonly="true"
                                   value="{{ user.username }}">
                            <p>无法更改用户名</p>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="email">电子邮件</label>

                        <div class="controls">
                            <input class="input-xlarge" id="email" name="user_email" size="30" type="text"
                                   value="{{ user.user_email }}">
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="location">所在地点</label>

                        <div class="controls">
                            <input class="input-xlarge" id="location" name="user_address" size="30" type="text"
                                   value="{{ user.user_address }}">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="signature">个性签名</label>

                        <div class="controls">
                            <textarea class="input-xlarge" id="signature" name="user_idiograph" size="30">{{ user.user_idiograph }}</textarea>
                        </div>
                    </div>

                    <div class="form-actions">
                        <input type="submit" class="span-primary submit_btn" data-loading-text="保存中.." value="保存设置">
                    </div>
                </form>
            </div>
        </div>
        <div class="panel">
            <div class="header">
                <span class="col_fade">更改头像</span>
            </div>
            <div class="inner">
                <form id="change_pass_form" class="form-horizontal" action={{url_for(
                    "topic.add_img")}} method="post" enctype=multipart/form-data>
                    <div class="control-group">
                        <div class="image-change control-label">
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="control-label" id="image-change">
                            <img src={{"/uploads/" + user.user_image + '?v=3&amp;s=120' }}>
                        </div>

                        <div class="controls">
                            <div class="form-actions">
                                <input type=file name=file>
                            </div>
                        </div>

                        <div class="form-actions">
                            <input type="submit" class="span-primary submit_btn" data-loading-text="保存中.." value="保存设置">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}
</div>


</body>
</html>