models/topic.py
import time
import json
from models import Model
from models.user import User
from models.mongua import Mongua
import logging
import os
import time
ogger = logging.getLogger("bbs")


class Cache(object):
    def get(self, key):
        pass

    def set(self, key, value):
        pass


class MemoryCache(Cache):
    def __init__(self):
        self.cache = {}

    def get(self, key):
        return self.cache[key]

    def set(self, key, value):
        self.cache[key] = value


class RedisCache(Cache):
    import redis
    redis_db = redis.StrictRedis(host='localhost', port=6379, db=0)

    def set(self, key, value):
        return RedisCache.redis_db.set(key, value)

    def get(self, key):
        return RedisCache.redis_db.get(key)


class Topic(Mongua):
    __fields__ = Mongua.__fields__ + [
        ('content', str, ''),
        ('title', str, -1),
        ('user_id', int, -1),
        ('board_id', int, -1),
        ('views', int, 0),
        ('last_time', int, 0)
    ]

    should_update_all = True
    # 1. memory cache
    cache = MemoryCache()
    # 2. redis cahce
    redis_cache = RedisCache()
    def to_json(self):
        d = dict()
        for k in Topic.__fields__:
            key = k[0]
            if not key.startswith('_'):
                d[key] = getattr(self,key)
        return json.dumps(d)

    @classmethod
    def from_json(cls, j):
        d = json.loads(j)

        instance = cls()
        for k, v in d.items():
            setattr(instance, k, v)
        return instance

    @classmethod
    def all_delay(cls):
        time.sleep(3)
        return Topic.all()

    @classmethod
    def get(cls, id):
        m = cls.find_by(id=id)
        m.views += 1
        m.save()
        return m

    def save(self):
        super(Topic, self).save()
        Topic.should_update_all = True

    @classmethod
    def cache_all(cls):
        if Topic.should_update_all:
            Topic.cache.set("topic_all", cls.all())
            Topic.should_update_all = False
        return Topic.cache.get("topic_all")

        # 2. redis cache
        if Topic.should_update_all:
            Topic.redis_cache.set('topic_all', json.dumps([i.to_json() for i in cls.all_delay()]))
            Topic.should_update_all = False
        j = json.loads(Topic.redis_cache.get('topic_all').decode('utf-8'))
        j = [Topic.from_json(i) for i in j]
        return j

    def replies(self):
        from .reply import Reply
        ms = Reply.find_all(topic_id=self.id)
        return ms

    def board(self):
        from .board import Board
        m = Board.find(self.board_id)
        return m

    def user(self):
        u = User.find(id=self.user_id)
        return u

    def other_topic(self):
        user = self.user()
        other_topic = user.user_topic()
        return other_topic

    def create_time(self):
        import datetime
        created_time = datetime.datetime.fromtimestamp(self.created_time)
        present_time = datetime.datetime.now()
        t = present_time - created_time

        if t.days != 0:
            return str(t.days) + '天前'
        else:
            sec = t.seconds
            if sec < 60:
                return str(sec) + '秒前'
            elif sec < 3600:
                return str(sec // 60) + '分钟前'
            else:
                return str(sec // 3600) + '小时前'

    def update_time(self):
        import datetime
        if self.last_time == 0:
            return '无人评论'
        created_time = datetime.datetime.fromtimestamp(self.last_time)
        present_time = datetime.datetime.now()
        t = present_time - created_time

        if t.days != 0:
            return str(t.days) + '天前'
        else:
            sec = t.seconds
            if sec < 60:
                return str(sec) + '秒前'
            elif sec < 3600:
                return str(sec // 60) + '分钟前'
            else:
                return str(sec // 3600) + '小时前'

routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.reply import Reply


main = Blueprint('reply', __name__)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()
    m = Reply.new(form, user_id=u.id)
    from .topic import Topic
    t = Topic.find_by(id=m.topic_id)
    t.last_time = m.created_time
    t.save()
    return redirect(url_for('topic.detail', id=m.topic_id))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    send_from_directory,
    abort,
)

from routes import *

from models.topic import Topic
from models.board import Board

from utils import allow_file
from models.user import User
from werkzeug.utils import secure_filename
from config import user_file_director
import os
import uuid


main = Blueprint('topic', __name__)

csrf_tokens = dict()


def current_user():
    # 从 session 中找到 user_id 字段, 找不到就 -1
    # 然后 User.find_by 来用 id 找用户
    # 找不到就返回 None
    uid = session.get('user_id', -1)
    u = User.find_by(id=uid)
    return u


# Topic
@main.route("/")
def index():
    # board_id = 2
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        # ms = Topic.all()
        ms = Topic.cache_all()
        # ms = Topic.all_delay()
    else:
        ms = Topic.find_all(board_id=board_id)
        # ms = Topic.cache_find(board_id)
    token = str(uuid.uuid4())
    u = current_user()
    if u is None:
        return redirect(url_for('.signin'))
    else:
        csrf_tokens['token'] = u.id
        bs = Board.all()
        return render_template("topic/index.html", user=u, ms=ms, token=token, bs=bs)


@main.route('/topic/<int:id>')
def detail(id):
    u = current_user()
    m = Topic.get(id)
    other_topic = m.other_topic()

    return render_template("topic/detail.html", user=u, topic=m, other_topic=other_topic)


@main.route("/topic/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()
    m = Topic.new(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/topic/delete")
def delete():
    id = int(request.args.get('id'))
    token = request.args.get('token')
    u = current_user()
    # 判断 token 是否是我们给的
    if token in csrf_tokens and csrf_tokens[token] == u.id:
        csrf_tokens.pop(token)
        if u is not None:
            print('删除 topic 用户是', u, id)
            Topic.delete(id)
            return redirect(url_for('.index'))
        else:
            abort(404)
    else:
        abort(403)


@main.route("/topic/new")
def new():
    u = current_user()
    bs = Board.all()
    return render_template("topic/new.html", user=u, bs=bs)


# login
@main.route("/signin")
def signin():
    u = current_user()
    return render_template("index.html", user=u)


@main.route("/register", methods=['POST'])
def register():
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.signin'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('.signin'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('.index'))


@main.route("/key_login", methods=['POST'])
def key_login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('topic.index'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('topic.index'))


# setting
@main.route('/setting')
def setting():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        return render_template('profile.html', user=u)


@main.route('/setting/user', methods=['POST'])
def setting_user():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        u.update(request.form)
        return redirect(url_for(".setting"))


@main.route('/addimg', methods=["POST"])
def add_img():
    u = current_user()

    if u is None:
        return redirect(url_for(".setting"))

    if 'file' not in request.files:
        return redirect(request.url)

    file = request.files['file']
    if file.filename == '':
        return redirect(request.url)

    if allow_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(user_file_director, filename))
        u.user_image = filename
        u.save()

    return redirect(url_for(".setting"))


@main.route("/uploads/<filename>")
def uploads(filename):
    return send_from_directory(user_file_director, filename)


@main.route("/logout")
def log_out():
    session.pop("user_id")
    return redirect(url_for(".index"))

templates/topic/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <script src="https://cdn.bootcss.com/marked/0.3.6/marked.min.js"></script>
    <script src="/static/js/marked.js"></script>
</head>
<body>
{% extends "base.html"%}
<div id="main">
    {% block sidebar %}
    <div id="sidebar">
        <div class="panel">
            <div class="header">
                <span class="col_fade">作者</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="/user/{{ topic.user().username }}">
                            <img src={{"/uploads/" + topic.user().user_image + '?v=3&amp;s=120'}} title="Wang-Xuan">
                        </a>
                        <span class="user_name"><a class="dark" href="/user/{{ topic.user().username }}">{{ topic.user().username }}</a></span>

                        <div class="board clearfix">
                            <div class="floor">
                                <span class="big">积分: 0 </span>
                            </div>
                        </div>
                        <div class="space clearfix"></div>
                        <span class="signature">
                            {{topic.user().user_idiograph}}
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel">
            <div class="header">
                <span class="col_fade">作者其它话题</span>
            </div>
            <div class="inner">
                <ul class="unstyled">
                    {% for t in other_topic %}
                    <li>
                        <div><a class="dark topic_title" href="{{ url_for('topic.detail', id=t.id) }}"
                                title="{{ t.title }}">{{ t.title }}</a>

                            </a>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    {% endblock %}

    {% block content %}
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
                <span class="topic_full_title">
                    {{ topic.title }}
                </span>
                <div class="changes">
                    <span>
                        发布于 {{topic.create_time()}}
                    </span>
                        <span>
                        作者
                        <a href="/user/{{ topic.user().username }}">{{ topic.user().username }}</a>
                    </span>
                        <span>
                        {{ topic.views }} 次浏览
                    </span>
                        <span>
                        来自 <a href="/topic?board_id={{ topic.board_id }}">{{ topic.board().title }}</a>
                    </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">
                        <div id="topic-content"></div>


                    </div>
                </div>
            </div>
        </div>
        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>
                    <!-- 过滤器 -->
                    {{ topic.replies() | count }} 回复
                </span>
            </div>
            {% for r in topic.replies() %}
            <div class='cell reply_area reply_item'>
                <div class='author_content'>
                    <a href="/user/{{ r.user().username }}" class="user_avatar">
                        <img src={{"/uploads/" + r.user().user_image + '?v=3&amp;s=120' }}
                        title="{{ r.user().username }}"/>
                    </a>
                    <div class='user_info'>
                        <a class='dark reply_author' href="/user/{{ r.user().username }}">
                            {{ r.user().username }}
                        </a>
                        <a class="reply_time">
                            {{ loop.index }}楼 • {{r.time()}}
                        </a>
                    </div>
                    <div class='user_action'>
                        <span>
                            <i class="fa up_btn
                              fa-thumbs-o-up
                              invisible" title="喜欢"></i>
                            <span class="up-count">
                            </span>
                        </span>
                    </div>
                </div>
                <div class='reply_content from-leiwei1991'>
                    <div class="markdown-text">
                        {{ r.content }}
                    </div>
                    <div class="markdown-topic">
                    </div>
                </div>
            </div>
            {% endfor %}
            <!--<div>-->
            <!--<form action="{{ url_for('reply.add') }}" method="post">-->
            <!--<input type="hidden" name="topic_id" value="{{ topic.id }}">-->
            <!--<textarea name="content"></textarea>-->
            <!--<button>添加回复</button>-->
            <!--</form>-->
            <!--</div>-->
        </div>
        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>添加回复</span>
            </div>
            <div class='inner reply'>
                <form id='reply_form' action="{{ url_for('reply.add') }}" method='post'>
                    <div class='markdown_editor in_editor'>
                        <div class='markdown_in_editor'>
                            <input type="hidden" name="topic_id" value="{{ topic.id }}">
                            <textarea class='editor' name='content' rows='8'></textarea>

                            <div class='editor_buttons'>
                                <input class='span-primary submit_btn' type="submit" data-loading-text="回复中.."
                                       value="回复">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div id="123"></div>
    {% endblock %}
</div>
<!-- 评论板块 -->
</div>
{% block script %}
<script class="hidden-content" type="gamle/text">{{ topic.content }}</script>
<script src="../static/js/detail.js"></script>
{% endblock %}
</body>
</html>

templates/topic/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
{% extends "base.html"%}
<div id="main">
    {% block content %}
    <div id="content">
        <div class="panel">
            <div class="header">
                <a href="/"
                   class="topic-tab current-tab">
                    全部
                </a>

                {% for b in bs %}
                <a href="?board_id={{ b.id }}"
                   class="topic-tab current-tab">
                    {{ b.title }}
                </a>
                {% endfor %}
            </div>
            <div class="inner post">
                <div class="topic_list">
                    {% for t in ms %}
                    <div class="cell">
                        <a class="last_time pull-right">
                            <span>最后回复</span>
                            <span class="last_active_time">{{ t.update_time() }}</span>
                        </a>
                        <div class="topic_title_wrapper">

                            <a class="user_avatar pull-left" href="/user/{{ t.user().username }}">
                                <img src={{ '/uploads/' + t.user().user_image + '?v=3&amp;s=120' }}
                                title="atian25"/>
                            </a>
                            <span class="topiclist-tab">{{ t.board().title }}</span>
                            <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
                            <span class="reply_count pull-left">
                                <span class="count_of_replies" title="回复数">
                                  {{ t.replies() | count }}
                                </span>
                                <span class="count_seperator">/</span>
                                <span class="count_of_visits" title='点击数'>
                                  {{ t.views }}
                                </span>
                            </span>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
</div>

<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>

templates/topic/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
{% extends "base.html"%}
<div id="main">
    {% block sidebar %}
    <div id="sidebar">
        <div class="panel">
            <div class="header">
                <span class="col_fade">Markdown 语法参考</span>
            </div>
            <div class="inner">
                <ol>
                    <li><tt>### 单行的标题</tt></li>
                    <li><tt>**粗体**</tt></li>
                    <li><tt>`console.log('行内代码')`</tt></li>
                    <li><tt>```js\n code \n```</tt> 标记代码块</li>
                    <li><tt>[内容](链接)</tt></li>
                    <li><tt>![文字说明](图片链接)</tt></li>
                </ol>
                <span><a href="https://segmentfault.com/markdown" target="_blank">Markdown 文档</a></span>
            </div>
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">话题发布指南</span>
            </div>
            <div class="inner">
                <ol>
                    <li>尽量把话题要点浓缩到标题里</li>
                    <li>代码含义和报错可在 <a href="http://segmentfault.com">SegmentFault</a> 提问</li>
                </ol>
            </div>
        </div>

    </div>
    {% endblock %}

    {% block content %}
    <div id="content">
        <div class="panel">
            <div class="inner post">
                <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                    <fieldset>
                        <textarea autofocus class='span9' id='title'
                              name='title' rows='1'
                              placeholder="标题字数 10 字以上"></textarea>
                        <span class="tab-selector">选择版块：</span>
                        <select name="board_id" id="board" required>
                            <option value="">请选择</option>
                            {% for b in bs %}
                            <option value="{{ b.id }}">{{ b.title }}</option>
                            {% endfor %}
                        </select>
                        <div class='markdown_editor in_editor'>
                            <div class='markdown_in_editor'>
                                <input type="hidden" name="reply_id" value="user.id">
                                <textarea class='editor' name='content' rows='20'
                                          placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                    <input type="submit" class='span-primary submit_btn' data-loading-text="提交中"
                                           value="提交">
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}
</div>

<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();



</script>
</body>
</html>

templates/topic/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
<div id="main">
    <div id="content">
        <div class="panel">
            <div class="inner post">
                <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                    <fieldset>
                        <textarea autofocus class='span9' id='title' name='title' rows='1'
                                  placeholder="标题字数 10 字以上"></textarea>
                        <div class='markdown_editor in_editor'>
                            <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20'
                                          placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                    <input type="submit" class='span-primary submit_btn' data-loading-text="提交中"
                                           value="提交">
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
<script>

  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();

</script>
</body>
</html>