models/user.py
from models import Model
from models.mongua import Mongua


class User(Model):
    """
    User 是一个保存用户数据的 model
    现在只有两个属性 username 和 password
    """

    def __init__(self, form):
        self.id = form.get('id', None)
        self.username = form.get('username', '')
        self.password = form.get('password', '')
        self.user_image = 'default.png'

    def salted_password(self, password, salt='$!@><?>HUI&DWQa`'):
        import hashlib
        def sha256(ascii_str):
            return hashlib.sha256(ascii_str.encode('ascii')).hexdigest()

        hash1 = sha256(password)
        hash2 = sha256(hash1 + salt)
        return hash2

    def hashed_password(self, pwd):
        import hashlib
        # 用 ascii 编码转换成 bytes 对象
        p = pwd.encode('ascii')
        s = hashlib.sha256(p)
        # 返回摘要字符串
        return s.hexdigest()

    @classmethod
    def register(cls, form):
        name = form.get('username', '')
        pwd = form.get('password', '')
        if len(name) > 2 and User.find_by(username=name) is None:
            u = User.new(form)
            u.password = u.salted_password(pwd)
            u.save()
            return u
        else:
            return None

    @classmethod
    def validate_login(cls, form):
        u = User(form)
        user = User.find_by(username=u.username)
        if user is not None and user.password == u.salted_password(u.password):
            return user
        else:
            return None


class User(Mongua):
    __fields__ = Mongua.__fields__ + [
        ('username', str, ''),
        ('password', str, ''),
        ('user_image', str, 'default.png'),
        ('user_address', str, ''),
        ('user_email', str, ''),
        ('user_idiograph', str, '这家伙很懒，什么个性签名都没有留下。')
    ]

    """
        User 是一个保存用户数据的 model
        现在只有两个属性 username 和 password
        """

    def __init__(self):
        self.user_image = 'default.png'

    def salted_password(self, password, salt='$!@><?>HUI&DWQa`'):
        import hashlib
        def sha256(ascii_str):
            return hashlib.sha256(ascii_str.encode('ascii')).hexdigest()

        hash1 = sha256(password)
        hash2 = sha256(hash1 + salt)
        return hash2

    def hashed_password(self, pwd):
        import hashlib
        # 用 ascii 编码转换成 bytes 对象
        p = pwd.encode('ascii')
        s = hashlib.sha256(p)
        # 返回摘要字符串
        return s.hexdigest()

    @classmethod
    def register(cls, form):
        name = form.get('username', '')
        pwd = form.get('password', '')
        if len(name) > 2 and User.find_by(username=name) is None:
            u = User.new(form)
            u.password = u.salted_password(pwd)
            u.save()
            return u
        else:
            return None

    def user_topic(self):
        from .topic import Topic
        t = Topic.find_all(user_id=self.id)
        return t

    def topic(self):
        from .topic import Topic
        t = Topic.find_all(id=self.id)
        return t

    def reply_topic(self):
        from .reply import Reply
        t = Reply.find_all(user_id=self.id)
        return t

    @classmethod
    def validate_login(cls, form):
        u = User()
        u.username = form.get("username", '')
        u.password = form.get("password", "")
        user = User.find_by(username=u.username)
        if user is not None and user.password == u.salted_password(u.password):
            return user
        else:
            return None

    def time(self):
        import datetime
        created_time = datetime.datetime.fromtimestamp(self.created_time)
        present_time = datetime.datetime.now()
        t = present_time - created_time

        if t.days != 0:
            return str(t.days) + '天前'
        else:
            sec = t.seconds
            if sec < 60:
                return str(sec) + '秒前'
            elif sec < 3600:
                return str(sec // 60) + '分钟前'
            else:
                return str(sec // 3600) + '小时前'

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    send_from_directory,
    abort,
)

from routes import *

from models.topic import Topic
from models.board import Board

from utils import allow_file
from models.user import User
from werkzeug.utils import secure_filename
from config import user_file_director
import os
import uuid


main = Blueprint('topic', __name__)

csrf_tokens = dict()


def current_user():
    # 从 session 中找到 user_id 字段, 找不到就 -1
    # 然后 User.find_by 来用 id 找用户
    # 找不到就返回 None
    uid = session.get('user_id', -1)
    u = User.find_by(id=uid)
    return u


# Topic
@main.route("/")
def index():
    # board_id = 2
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        # ms = Topic.all()
        ms = Topic.cache_all()
        # ms = Topic.all_delay()
    else:
        ms = Topic.find_all(board_id=board_id)
        # ms = Topic.cache_find(board_id)
    token = str(uuid.uuid4())
    u = current_user()
    if u is None:
        return redirect(url_for('.signin'))
    else:
        csrf_tokens['token'] = u.id
        bs = Board.all()
        return render_template("topic/index.html", user=u, ms=ms, token=token, bs=bs)


@main.route('/topic/<int:id>')
def detail(id):
    u = current_user()
    m = Topic.get(id)
    other_topic = m.other_topic()

    return render_template("topic/detail.html", user=u, topic=m, other_topic=other_topic)


@main.route("/topic/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()
    m = Topic.new(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/topic/delete")
def delete():
    id = int(request.args.get('id'))
    token = request.args.get('token')
    u = current_user()
    # 判断 token 是否是我们给的
    if token in csrf_tokens and csrf_tokens[token] == u.id:
        csrf_tokens.pop(token)
        if u is not None:
            print('删除 topic 用户是', u, id)
            Topic.delete(id)
            return redirect(url_for('.index'))
        else:
            abort(404)
    else:
        abort(403)


@main.route("/topic/new")
def new():
    u = current_user()
    bs = Board.all()
    return render_template("topic/new.html", user=u, bs=bs)


# login
@main.route("/signin")
def signin():
    u = current_user()
    return render_template("index.html", user=u)


@main.route("/register", methods=['POST'])
def register():
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.signin'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('.signin'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('.index'))


@main.route("/key_login", methods=['POST'])
def key_login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('topic.index'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('topic.index'))


# setting
@main.route('/setting')
def setting():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        return render_template('profile.html', user=u)


@main.route('/setting/user', methods=['POST'])
def setting_user():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        u.update(request.form)
        return redirect(url_for(".setting"))


@main.route('/addimg', methods=["POST"])
def add_img():
    u = current_user()

    if u is None:
        return redirect(url_for(".setting"))

    if 'file' not in request.files:
        return redirect(request.url)

    file = request.files['file']
    if file.filename == '':
        return redirect(request.url)

    if allow_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(user_file_director, filename))
        u.user_image = filename
        u.save()

    return redirect(url_for(".setting"))


@main.route("/uploads/<filename>")
def uploads(filename):
    return send_from_directory(user_file_director, filename)


@main.route("/logout")
def log_out():
    session.pop("user_id")
    return redirect(url_for(".index"))

routes/user.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *
from models.user import User
from models.topic import Topic
from models.mail import Mail


main = Blueprint('user', __name__)


@main.route("/<username>")
def user(username):
    u = current_user()
    user = User.find_by(username=username)
    t = user.user_topic()

    topics = user.reply_topic()
    a = []
    test = []
    for topic in topics:
        if topic.topic_id not in test:
            test.append(topic.topic_id)
            a.append(Topic.find_all(id=topic.topic_id))
    return render_template("user/user_detail.html", username=username, user_slide=u, user=user, ms=t, a=a)


@main.route("/<username>/mail")
def mail(username):
    u = current_user()
    user = User.find_by(username=username)
    return render_template("mail/send_mail.html", username=username, receiver_user=user)


@main.route("/mail_add", methods=["POST"])
def mail_add():
    form = request.form
    mail = Mail.new(form)
    # 为了安全
    mail.set_sender(current_user().id)
    return redirect(url_for("mail.index"))

templates/user/user_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ 个人主页 }}</title>
</head>
<body>
{% extends "base.html"%}
<div id="main">
    {% block sidebar %}
        <div id="sidebar">
            <div class="panel">
                <div class="header">
                    <span class="col_fade">个人信息</span>
                </div>
                <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="/user/{{ user.username }}">
                            <img src={{"/uploads/" + user.user_image + '?v=3&amp;s=120'}} title="Wang-Xuan">
                        </a>
                        <span class="user_name"><a class="dark" href="/user/{{ user.username }}">{{user.username}}</a></span>

                        <div class="board clearfix">
                            <div class="floor">
                                <span class="big">积分: 0 </span>
                            </div>
                        </div>
                        <div class="space clearfix"></div>
                        <span class="signature">
                            {{user.user_idiograph}}
                        </span>
                    </div>
                </div>
            </div>
            </div>
            <div class="panel">
                    <div class="inner">
                        <a href= {{username + "/mail"}} class="create_topic_btn">
                            <span class="span-success">发送私信</span>
                        </a>
                    </div>
            </div>
        </div>
    {% endblock %}

    {% block content %}
    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="/">主页</a><span class="divider">/</span></li>
                    <li class="active">用户信息</li>
                </ul>
            </div>
            <div class="inner userinfo">
                <div class="user_big_avatar">
                    <img src={{"/uploads/" + user.user_image + '?v=3&amp;s=120' }} class="user_avatar"
                    title="{{ user.username }}">
                </div>
                <a class="dark">{{ user.username }}</a>

                <div class="user_profile">
                    <ul class="unstyled">
                        <span class="big">0</span> 积分
                        <li>
                            <i class="fa fa-lg fa-fw fa-home"></i>
                            <a class="dark">邮件：{{ user.user_email }}</a>
                        </li>
                        <li>
                            <i class="fa fa-lg fa-fw fa-github"></i>
                            <a class="dark">
                                地点：{{ user.user_address }}
                            </a>
                        </li>
                        <li>
                            <i class="fa fa-lg fa-fw fa-github"></i>
                            <a class="dark">
                                个性签名：{{ user.user_idiograph }}
                            </a>
                        </li>
                    </ul>
                </div>
                <p class="col_fade">注册时间 {{ user.time() }}</p>
            </div>
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">最近创建的话题</span>
            </div>

            <div class="inner post">
                <div class="topic_list">
                    {% for t in ms %}
                    <div class="cell">
                        <a class="last_time pull-right">
                            <span>最后回复</span>
                            <span class="last_active_time">{{ t.update_time() }}</span>
                        </a>
                        <div class="topic_title_wrapper">

                            <a class="user_avatar pull-left" href="/user/{{ t.user().username }}">
                                <img src={{ '/uploads/' + t.user().user_image + '?v=3&amp;s=120' }}
                                title="atian25"/>
                            </a>
                            <span class="topiclist-tab">{{ t.board().title }}</span>
                            <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
                            <span class="reply_count pull-left">
                                <span class="count_of_replies" title="回复数">
                                  {{ t.replies() | count }}
                                </span>
                                <span class="count_seperator">/</span>
                                <span class="count_of_visits" title='点击数'>
                                  {{ t.views }}
                                </span>
                            </span>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">最近参与的话题</span>
            </div>

            <div class="inner post">
                <div class="topic_list">
                    {% for a1 in a %}
                    {% for t in a1 %}
                    <div class="cell">
                        <a class="last_time pull-right">
                            <span>最后回复</span>
                            <span class="last_active_time">{{ t.update_time() }}</span>
                        </a>
                        <div class="topic_title_wrapper">

                            <a class="user_avatar pull-left" href="/user/{{ t.user().username }}">
                                <img src={{ '/uploads/' + t.user().user_image + '?v=3&amp;s=120' }}
                                title="atian25"/>
                            </a>
                            <span class="topiclist-tab">{{ t.board().title }}</span>
                            <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
                            <span class="reply_count pull-left">
                                <span class="count_of_replies" title="回复数">
                                  {{ t.replies() | count }}
                                </span>
                                <span class="count_seperator">/</span>
                                <span class="count_of_visits" title='点击数'>
                                  {{ t.views }}
                                </span>
                            </span>
                        </div>
                    </div>
                    {% endfor %}
                    {% endfor %}
                </div>
            </div>

        </div>
    </div>
    {% endblock %}
</div>


</body>
</html>